### ISSUE TITLE
La foto, dio, la foto

### ISSUE THREAD

**Issue by nusco** [coders51/ExMachinaConf#2]
Bella la home, ma le foto sono irritanti. Chi sono quegli stronzi con i cappellini da baseball? E quelle grannies che si fischiano i mortacci loro? È una conferenza di informatica, non un happening di musica country, cristo. Non abbiamo un'immagine meno sgodevole?

**Comment by nusco** [comment]
Fixed by bcec21d044108a3f2fbeaa45f414f06a300fb4bb, se a voi piace.

**Comment by nusco** [comment]
Ripensandoci, riapro le issue che avevo chiuso, e lascio che le chiudiate voi se ritenete che siano ok.

**Comment by finelli** [comment]
Per me ok così, ma ok anche le _grannies_.

Il _country_ è quel genere simile al _western_?

**Comment by nunziofiore** [comment]
Se a voi piace non discuto e lascio cosi'

"esiste il pescecane il pesce gatto e il pesce ratto possono piacere o non piacere, e su questo io non discuto, ad ogni modo a me la grigliata di pesce ratto piace da morire!"
