### ISSUE TITLE
Aggiustamenti pagina organizers

### ISSUE THREAD

**Issue by nusco** [coders51/ExMachinaConf#4]
Stupende le foto degli organizers, ma una è duplicata. Capisco che mostra due personaggi, ma confonde. Forse è meglio metterli insieme (Tector and Lyle Gorch), togliere l'indirizzo dell'agile gigi e lasciare quello di agile42.

Inoltre non mi sembra il caso di mettere un pulsante "Buy Tickets Now!" ogni tre righe. Sembriamo disperati. Quelli sulla home page bastano e avanzano. (O forse questi pulsanti sono intesi come punto di contatto per gli organizzatori?).

**Comment by nusco** [comment]
Ho fatto: 90be69dd4f6cb443a7064cf01be19a70facbef3f

Ditemi se vi piace. FYI, sto già diffondendo il link alla pagina presso pochi fini cultori.

**Comment by nunziofiore** [comment]
giusto il raggruppamento. Ho cambiato solo l'alternanza destra e sinistra delle immagini
