### ISSUE TITLE
Il logo fa schifo al cazzo

### ISSUE THREAD

**Issue by nusco** [coders51/ExMachinaConf#5]
Capisco che a Nunzio il logo non piaccia. In effetti volevamo fare una cosa buffa e informale. Ma se non ci piace, facciamone un altro. Molto meglio che visualizzarlo in un quadrato di 2x2 cm, che sembra una cacata di mosca sul monitor. Nemmeno noi che l'abbiamo fatto riusciamo a capire cosa c'è dentro.

Visto che ci siamo: il logo è talmente piccolo che non si capisce nemmeno che colore abbia, quindi non è il caso di usare il simpatico schema colore "liquid shit" solo perché il logo se lo porta dietro. Quindi se lo rifacciamo, cambiamo anche lo schema colore. Facciamo giallo e nero, e bona l'è.

**Comment by nusco** [comment]
Faccio una cosa: spalmo il logo in grande al posto della foto dei derelitti al concerto country, e ne faccio una versione piccola, solo geometrie (senza disegnini) in giallo e nero. Vediamo come viene.

**Comment by nusco** [comment]
Fixed by bcec21d044108a3f2fbeaa45f414f06a300fb4bb

**Comment by nunziofiore** [comment]
Il popolo ha salvato Barabba
