### ISSUE TITLE
Effetto geocities

### ISSUE THREAD

**Issue by nusco** [coders51/ExMachinaConf#7]
Quando si passa da una pagina all'altra (per esempio, da "Organizers" a "Home") si vede un allegro effetto Geocities, per cui si vede caricare prima il logo, e poi il resize di tutti gli elementi della pagina. L'effetto dura un piacevolissimo secondo, che è abbastanza per causare una simpatica crisi epilettica. Tenete presente che ho il MacBook più veloce attualmente in commercio e una connessione in fibra ottica. L'effetto si vede bene sul sito online, ma non quando si carica una pagina in locale.

Il problema potrebbe essere il fatto che il logo, che viene visualizzato in dimensioni più piccole della nerchia di Finelli, è in realtà enorme come lo scroto di Bettazzoni. Forse è meglio farne il resize. Ci provo io ora che lo modifico.

**Comment by nusco** [comment]
Maybe fixed by bcec21d044108a3f2fbeaa45f414f06a300fb4bb? Nunz, metti online che controlliamo?

**Comment by nusco** [comment]
Vedo ora che è _già_ online. Non sapevo che ci fosse il deploy automatico. Be', l'effetto Geocities è ancora lí. @nunziofiore, qualche idea?

**Comment by finelli** [comment]
In ufficio si pensava di chiuderla così, con la home page e i tuoi commenti. Non è necessario altro, secondo noi.

**Comment by nusco** [comment]
I colori.

**Comment by finelli** [comment]
... a coloro che non sanno ciò che significano i colori, i colori hanno un volto, e bisogna farsi amico il colore, colore e terrore morale sono i tuoi amici, ma se non lo sono, essi sono dei nemici da temere, sono dei veri nemici ...

**Comment by finelli** [comment]
(con un panno bagnato mi sto asciugando la testa)

**Comment by nunziofiore** [comment]
io non riesco a riprodurlo.
Mi alleghi un mini video?

**Comment by nusco** [comment]
Guarda, ora che il sito in generale è molto bellino, direi che non vale la pena di preoccuparsi di questo dettaglio. Non lo noterà nessuno, sono io che sono ipersensibile a tutte le questioni di UI. Lo chiudo.
