### ISSUE TITLE
Nuovo schema colore

### ISSUE THREAD

**Issue by nusco** [coders51/ExMachinaConf#8]
Ora che ho cambiato i logo con bcec21d044108a3f2fbeaa45f414f06a300fb4bb, questa issue e la #5 dovrebbero essere chiuse. Prima di chiudere anche questa, mi servono due cose da voi:

1. Una conferma che cosí i logo e la pagina in generale vanno bene.
2. Un nuovo schema colore che rispecchi il nero e giallo-oro del logo.

Nunz, cambi i colori? Vedi anche la issue #3.

**Comment by nunziofiore** [comment]
Ho cambiato i colori partendo ora quindi dal nero del logo a una sfumatura piu' chiara che ho messo a un delicato 666666 che avendo un palese richiamo satanico porta sempre bene

**Comment by nusco** [comment]
Ottimo! La sfumatura sui pulsanti ora è perfetta.
Ho cambiato lo sfondo dell'immagine di conseguenza, perché con i nuovi pulsanti la gradazione dei colori si era sfasata.
Resta un mix di colori freddi e caldi che mi urta, ma ci si può convivere.
